# Generated by Django 4.2.1 on 2023-07-01 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_publication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('pk',), 'permissions': [('set_published', 'Can publish posts')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
