# Generated by Django 4.2.1 on 2023-07-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_client_mailing_message_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='body',
        ),
        migrations.AddField(
            model_name='mailing',
            name='body',
            field=models.TextField(default=1, verbose_name='Тело письма'),
            preserve_default=False,
        ),
    ]
